version: '3.1'
services:
  dbpostgresql:
    image: postgres
    ports:
      - "5560:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo-list
