name: Build Project (Java 21) - master branch

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Verify Docker is running
        run: docker info

#      - name: Build and Test with Maven
#        env:
#          TESTCONTAINERS_RYUK_DISABLED: "true"
#        run: mvn clean install